<?php

namespace ContainerYV8As8M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlertFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AlertFormType' shared autowired service.
     *
     * @return \App\Form\AlertFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AlertFormType.php';

        return $container->privates['App\\Form\\AlertFormType'] = new \App\Form\AlertFormType();
    }
}
