<?php

namespace ContainerYV8As8M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionsFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TransactionsFormType' shared autowired service.
     *
     * @return \App\Form\TransactionsFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TransactionsFormType.php';

        return $container->privates['App\\Form\\TransactionsFormType'] = new \App\Form\TransactionsFormType(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
