<?php

namespace ContainerYV8As8M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getXeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\XeController' shared autowired service.
     *
     * @return \App\Controller\XeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/XeController.php';

        $container->services['App\\Controller\\XeController'] = $instance = new \App\Controller\XeController(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->privates['App\\Repository\\XeRepository'] ?? $container->load('getXeRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\AlertRepository'] ?? $container->load('getAlertRepositoryService')), ($container->privates['App\\Repository\\TransactionsRepository'] ?? $container->load('getTransactionsRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\XeController', $container));

        return $instance;
    }
}
