<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNhRQ28W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNhRQ28W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNhRQ28W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNhRQ28W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNhRQ28W\App_KernelDevDebugContainer([
    'container.build_hash' => 'NhRQ28W',
    'container.build_id' => '79194ca9',
    'container.build_time' => 1667504469,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNhRQ28W');
