<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'today' => [[], ['_controller' => 'App\\Controller\\XeController::index'], [], [['text', '/xe/exchange/today']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\XeController::second'], [], [['text', '/xe/exchange/home']], [], [], []],
    'add' => [[], ['_controller' => 'App\\Controller\\XeController::add'], [], [['text', '/xe/exchange/add']], [], [], []],
    'view' => [[], ['_controller' => 'App\\Controller\\XeController::view'], [], [['text', '/xe/exchange/view']], [], [], []],
    'delete' => [['id'], ['_controller' => 'App\\Controller\\XeController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/xe/exchange/delete']], [], [], []],
    'deletealert' => [['id'], ['_controller' => 'App\\Controller\\XeController::deletealert'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/xe/exchange/deletealert']], [], [], []],
    'alert' => [[], ['_controller' => 'App\\Controller\\XeController::alert'], [], [['text', '/xe/exchange/alert']], [], [], []],
    'addalert' => [[], ['_controller' => 'App\\Controller\\XeController::create'], [], [['text', '/xe/exchange/addalert']], [], [], []],
    'app_logout' => [[], [], [], [['text', '/logout']], [], [], []],
];
